# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_bnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='bnc/')),
            ],
        ),
        migrations.CreateModel(
            name='img_gray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='gray/')),
            ],
        ),
        migrations.CreateModel(
            name='img_h',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='h/')),
            ],
        ),
        migrations.CreateModel(
            name='img_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='s/')),
            ],
        ),
        migrations.CreateModel(
            name='img_v',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='v/')),
            ],
        ),
    ]
