# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi', '0002_img_bnc_img_gray_img_h_img_s_img_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_ciri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.FloatField()),
                ('s', models.FloatField()),
                ('v', models.FloatField()),
                ('cont0', models.FloatField()),
                ('cont45', models.FloatField()),
                ('cont90', models.FloatField()),
                ('cont135', models.FloatField()),
                ('diss0', models.FloatField()),
                ('diss45', models.FloatField()),
                ('diss90', models.FloatField()),
                ('diss135', models.FloatField()),
                ('asm0', models.FloatField()),
                ('asm45', models.FloatField()),
                ('asm90', models.FloatField()),
                ('asm135', models.FloatField()),
                ('ener0', models.FloatField()),
                ('ener45', models.FloatField()),
                ('ener90', models.FloatField()),
                ('ener135', models.FloatField()),
                ('homo0', models.FloatField()),
                ('homo45', models.FloatField()),
                ('homo90', models.FloatField()),
                ('homo135', models.FloatField()),
                ('corr0', models.FloatField()),
                ('corr45', models.FloatField()),
                ('corr90', models.FloatField()),
                ('corr135', models.FloatField()),
            ],
        ),
    ]
